name: ci
on: [push, pull_request]
jobs:
  build-and-deploy:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install and Test ğŸ”§
        run: |
          npm install
          npm run lint

      - name: Build ğŸ™…â€â™€ï¸
        run: |
          npm run build

      - name: Deploy ğŸš€
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: master
          FOLDER: docs/.vuepress/dist
          CLEAN: true
